import type { PeopleSnapshot } from "./people";

/** wrapRuns joins runs with a space and trims each, so keep punctuation inside one run. */
export type ReportRun = { text: string; bold?: boolean; muted?: boolean };
/** A plain string is one regular run. */
export type ReportText = string | ReportRun[];
/** `lines` puts each entry on its own line inside the cell. */
export type ReportCell = ReportText | { lines: ReportText[] };
/**
 * Widths are relative; the renderer scales them to the 500pt content width.
 * `nowrap` is for IDs and card numbers: the text shrinks to fit rather than
 * breaking mid-number.
 */
type ReportColumn = {
  title: string;
  width: number;
  align?: "left" | "right";
  nowrap?: boolean;
};
/** No name prints a blank "Printed name" line. */
export type ReportSigner = { name?: string; title?: string };

export type ReportBlock =
  | { kind: "paragraph"; text: ReportText }
  | { kind: "fields"; items: { label: string; value: ReportText }[] }
  | { kind: "blank"; label: string }
  | {
      kind: "table";
      columns: ReportColumn[];
      rows: ReportCell[][];
      empty: string;
    }
  | { kind: "signatures"; label: string; signers: ReportSigner[] }
  | { kind: "note"; text: string };

/** letter: formal correspondence, with no "Generated by" line. report: a record, with that line under the title. */
export type ReportDocument = {
  kind: "letter" | "report";
  title: string;
  subtitle?: string;
  blocks: ReportBlock[];
};

export type ExportParam = {
  name: string;
  label: string;
  /**
   * date: YYYY-MM-DD, required unless `optional`.
   * text: may be blank; previews must never depend on text params, so the
   * page doesn't refresh when one changes.
   * term: "" or an academic year from academicTerms(); rendered as a select.
   */
  kind: "date" | "text" | "term";
  optional?: boolean;
  maxLength?: number;
  /** text: input placeholder. term: label of the blank option. */
  placeholder?: string;
};
export type ExportParamValues = Record<string, string>;
export type ExportContext = {
  now: Date;
  params: ExportParamValues;
  /** Memoised per request, so every report in one listing shares a single exec and signup read. */
  people: () => Promise<PeopleSnapshot>;
};

export type ExportPreview = {
  summary: string;
  /** Things to check before sending. Shown on the page only, never in the PDF. */
  warnings?: string[];
  /** Shown on the page only, never in the PDF. */
  attention?: { label: string; people: { name: string; detail: string }[] };
};

export type ExportMeta = {
  id: string;
  title: string;
  description: string;
  confidential: boolean;
  params: ExportParam[];
  defaults?: (now: Date) => ExportParamValues;
  /** Runs after the per-kind checks; a string goes back to the client as a 400. */
  validate?: (values: ExportParamValues, now: Date) => string | null;
};

/** `load` may read the database but never a live service; `preview` and `render` are pure. */
export type ExportReport<Data> = ExportMeta & {
  load: (ctx: ExportContext) => Promise<Data>;
  preview: (data: Data, ctx: ExportContext) => ExportPreview;
  render: (data: Data, ctx: ExportContext) => ReportDocument;
};

export type ExportSummary = Pick<
  ExportMeta,
  "id" | "title" | "description" | "confidential" | "params"
> & {
  defaults: ExportParamValues;
  preview: ExportPreview | null;
};
export type ExportListing = { reports: ExportSummary[] };
